### ISSUE TITLE
A little more information about this project?

### ISSUE THREAD

**Issue by RDKRACZ** [Stefan0436/Cyan#5]
- How does Cyan's Modkit compare to Fabric and Forge one?
- What is no completed yet?
- Are there any Cyan mods available already?
- Does running Cyan-Fabric affect performance more than running just Fabric?
- Is it also compatible with [Quilt](https://quiltmc.org/)?
- Do You have a Discord server?

**Comment by SkySwimmer** [comment]
I am a bit late, but i will try to answer your questions.

- Cyan's ModKit is intended to be compatible with Forge, Fabric and Paper.
  - Cyan's ModKit uses the official class namings, so it is quite different from Fabric and Forge.
  - Cyan's events run asynchronously
  - The Modding Toolkit is still pretty unfinished, more features will be added in the future
- Cyan is not complete, but it can already load mods and coremods.
- There are a few mods available, the mods i have created are on my new [GitHub profile](https://github.com/SkySwimmer)
- About CyanFabric, CyanPaper and CyanForge: it is slower when running Cyan, this is caused by FLUID's mappings processor used to remap transformers before applying them, this is not really a problem when you are ingame.
- Cyan is currently not compatible with Quilt, but i might add support for it in the future
- I do not have a public Discord server and i don't think i am going to create one yet, maybe in the future

\- Sky Swimmer

**Comment by Rajbir98** [comment]
It will be awesome to see things like this
